module_name: TextBanner
compatible_versions: 1.0.0+
author: Michael Rouse
category: front office
tags:
  - advertising
  - banner
  - images
  - gdpr
  - textbanner
description_short: The Text Banner module allows you to have a text-only banner at the top of your shop.
description: description.md
images:
  - image-1.png
gdpr_compliant: true
license: MIT
php_version:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
